name: FaceLink
options:
  bundleIdPrefix: io.github.kmpfacelink
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"

configFiles:
  Debug: Live2DConfig.xcconfig
  Release: Live2DConfig.xcconfig

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    FRAMEWORK_SEARCH_PATHS:
      - $(inherited)
      - $(SRCROOT)/../kmp-facelink-live2d/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
    SWIFT_INCLUDE_PATHS:
      - $(inherited)
      - $(SRCROOT)/../kmp-facelink-live2d/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/KMPFaceLink.framework/Modules
    # Live2D bridging header and C++17 are always needed (CubismBridge.mm compiles as stub without SDK)
    SWIFT_OBJC_BRIDGING_HEADER: FaceLink/Live2D/FaceLink-Bridging-Header.h
    CLANG_CXX_LANGUAGE_STANDARD: c++17

packages:
  RiveRuntime:
    url: https://github.com/rive-app/rive-ios
    from: "6.5.0"

targets:
  FaceLink:
    type: application
    platform: iOS
    sources:
      - path: FaceLink
      - path: FaceLink/Resources/Live2D
        type: folder
        optional: true
        buildPhase: resources
      # CubismNativeFramework C++ sources (Metal renderer only)
      - path: ../live2d/ios/Framework/src
        optional: true
        excludes:
          - "Rendering/D3D9/**"
          - "Rendering/D3D11/**"
          - "Rendering/Vulkan/**"
          - "Rendering/OpenGL/**"
          - "**/CMakeLists.txt"
          - "**/*.metal"
        compilerFlags:
          - "-fno-objc-arc"
      # Metal shader compiled separately (without -std=c++17)
      - path: ../live2d/ios/Framework/src/Rendering/Metal/MetalShaders.metal
        optional: true
    dependencies:
      - framework: ../kmp-facelink-live2d/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/KMPFaceLink.framework
        embed: false
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - package: RiveRuntime
    preBuildScripts:
      - name: Build KMP Framework
        script: |
          cd "$SRCROOT/.."
          ./gradlew :kmp-facelink-live2d:embedAndSignAppleFrameworkForXcode
        basedOnDependencyAnalysis: false
    info:
      path: FaceLink/Info.plist
      properties:
        NSCameraUsageDescription: "Face tracking requires camera access"
        NSMicrophoneUsageDescription: "Voice features require microphone access"
        UIRequiredDeviceCapabilities:
          - arkit
          - front-facing-camera
        UILaunchScreen: {}
